using GravitonEcoWEBmvc.Models.DataBaseModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System.Net;

namespace GravitonEcoWEBmvc.Services.DataBase
{
    public class SqliteDbContext : IdentityDbContext<IdentityUser>
    {
        public DbSet<GroupModel> GroupModels { get; set; }
        public DbSet<ModbusParametrModel> ModbusParametrs { get; set; }
        public DbSet<DeviceConnectionModel> DeviceConnectionModels { get; set; }

        public SqliteDbContext(DbContextOptions<SqliteDbContext> options) : base(options) { }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // Связь группы с ModbusParametrModel как основные параметры
            modelBuilder.Entity<GroupModel>()
                .HasMany(g => g.ModbusParametrs)
                .WithOne(p => p.Group)
                .HasForeignKey(p => p.GroupId)
                .OnDelete(DeleteBehavior.Restrict);

            // Связь группы с ModbusParametrModel как калибровочные параметры
            modelBuilder.Entity<GroupModel>()
                .HasMany(g => g.CalibrationParameters)
                .WithOne(p => p.CalibrationGroup)
                .HasForeignKey(p => p.CalibrationGroupId)
                .OnDelete(DeleteBehavior.Restrict);

            modelBuilder.Entity<DeviceConnectionModel>().HasData(
                    new DeviceConnectionModel { Id = 1, IpAddres = "10.10.10.107", Port = 5502 }
                );


            modelBuilder.Entity<GroupModel>().HasData(
            new GroupModel { Id = 1, GroupName = "Метеорологические параметры", DisplayFormat = 1 },
            new GroupModel { Id = 2, GroupName = "Газоанализатор", DisplayFormat = 1 },
            new GroupModel { Id = 3, GroupName = "Измеритель частиц пыли", DisplayFormat = 1 },
            new GroupModel { Id = 4, GroupName = "Монитор воздействий", DisplayFormat = 1 },
            new GroupModel { Id = 5, GroupName = "Параметры измерительной камеры", DisplayFormat = 1 },
            new GroupModel { Id = 6, GroupName = "Калибровка метеорологических параметров (НЕТ адресов регистров)", DisplayFormat = 2 },
            new GroupModel { Id = 7, GroupName = "Калибровка Газоанализатора", DisplayFormat = 2 },
            new GroupModel { Id = 8, GroupName = "Калибровка дополнительных входов", DisplayFormat = 2 },
            new GroupModel { Id = 9, GroupName = "Сервисные параметры", DisplayFormat = 2 }
        );

            modelBuilder.Entity<ModbusParametrModel>().HasData(


            new ModbusParametrModel
            {
                Id = 1,
                ParametrName = "Температура внеш (- 45 до +45°С)",
                GroupId = 1,
                CalibrationGroupId = 6,
                DeviceAddress = 2,
                RegisterCurrentValue = 5,
                RegisterPorog1 = 20,
                RegisterPorog2 = 21,
                RegisterIncrement = 22,
                RegisterPeriod = 23,
                RegisterAlarm1 = 15,
                RegisterAlarm2 = 16,
                RegisterAlarm3 = 17,
                RegisterOffset = 532,
                RegisterConstant = 533,
                RegisterValue = 534,
                RegisterCalibrationPeriod = 535,
                IsCalibration = true,
                IsReserved = false,
                ReservedAddress = null,
            },
            new ModbusParametrModel
            {
                Id = 2,
                ParametrName = "Отн.Влажность внеш (0 - 98 %)",
                GroupId = 1,
                CalibrationGroupId = 6,
                DeviceAddress = 2,
                RegisterCurrentValue = 6,
                RegisterPorog1 = 24,
                RegisterPorog2 = 25,
                RegisterIncrement = 26,
                RegisterPeriod = 27,
                RegisterAlarm1 = 18,
                RegisterAlarm2 = 19,
                RegisterAlarm3 = 20,
                RegisterOffset = 536,
                RegisterConstant = 537,
                RegisterValue = 538,
                RegisterCalibrationPeriod = 539,
                IsCalibration = true,
                IsReserved = false,
                ReservedAddress = null,
            },
            new ModbusParametrModel
            {
                Id = 3,
                ParametrName = "Атм.Дав-ние (650 - 1200 hPa)",
                GroupId = 1,
                CalibrationGroupId = 6,
                DeviceAddress = 1,
                RegisterCurrentValue = 1,
                RegisterPorog1 = 4,
                RegisterPorog2 = 5,
                RegisterIncrement = 6,
                RegisterPeriod = 7,
                RegisterAlarm1 = 3,
                RegisterAlarm2 = 4,
                RegisterAlarm3 = 5,
                RegisterOffset = 548,
                RegisterConstant = 549,
                RegisterValue = 550,
                RegisterCalibrationPeriod = 551,
                IsCalibration = true,
                IsReserved = false,
                ReservedAddress = null,
            },
            new ModbusParametrModel
            {
                Id = 4,
                ParametrName = "Доп. вход 1",
                GroupId = 1,
                CalibrationGroupId = 8,
                DeviceAddress = 1,
                RegisterCurrentValue = 7,
                RegisterPorog1 = 28,
                RegisterPorog2 = 29,
                RegisterIncrement = 30,
                RegisterPeriod = 31,
                RegisterAlarm1 = 21,
                RegisterAlarm2 = 22,
                RegisterAlarm3 = 23,
                RegisterOffset = 536,
                RegisterConstant = 537,
                RegisterValue = 538,
                RegisterCalibrationPeriod = 544,
                IsCalibration = true,
                IsReserved = false,
                ReservedAddress = null,
            },
            new ModbusParametrModel
            {
                Id = 5,
                ParametrName = "Доп. вход 2",
                GroupId = 1,
                CalibrationGroupId = 8,
                DeviceAddress = 1,
                RegisterCurrentValue = 2,
                RegisterPorog1 = 8,
                RegisterPorog2 = 9,
                RegisterIncrement = 10,
                RegisterPeriod = 11,
                RegisterAlarm1 = 6,
                RegisterAlarm2 = 7,
                RegisterAlarm3 = 8,
                RegisterOffset = 540,
                RegisterConstant = 541,
                RegisterValue = 542,
                RegisterCalibrationPeriod = 543,
                IsCalibration = true,
                IsReserved = false,
                ReservedAddress = null,

            },
            new ModbusParametrModel
            {
                Id = 6,
                ParametrName = "CO (0 - 40 000 ppb)",
                GroupId = 2,
                CalibrationGroupId = 7,
                DeviceAddress = 1,
                RegisterCurrentValue = 10,
                RegisterPorog1 = 40,
                RegisterPorog2 = 41,
                RegisterIncrement = 42,
                RegisterPeriod = 43,
                RegisterAlarm1 = 30,
                RegisterAlarm2 = 31,
                RegisterAlarm3 = 32,
                RegisterOffset = 520,
                RegisterConstant = 521,
                RegisterValue = 522,
                RegisterCalibrationPeriod = 523,
                IsCalibration = false,
                IsReserved = false,
                ReservedAddress = null,
            },
            new ModbusParametrModel
            {
                Id = 7,
                ParametrName = "NO (0 - 1 000 ppb)",
                GroupId = 2,
                CalibrationGroupId = 7,
                DeviceAddress = 1,
                RegisterCurrentValue = 12,
                RegisterPorog1 = 48,
                RegisterPorog2 = 49,
                RegisterIncrement = 50,
                RegisterPeriod = 51,
                RegisterAlarm1 = 36,
                RegisterAlarm2 = 37,
                RegisterAlarm3 = 38,
                RegisterOffset = 512,
                RegisterConstant = 513,
                RegisterValue = 514,
                RegisterCalibrationPeriod = 515,
                IsCalibration = false,
                IsReserved = false,
                ReservedAddress = null,
            },
            new ModbusParametrModel
            {
                Id = 8,
                ParametrName = "NO2 (0 - 1 000 ppb)",
                GroupId = 2,
                CalibrationGroupId = 7,
                DeviceAddress = 1,
                RegisterCurrentValue = 13,
                RegisterPorog1 = 52,
                RegisterPorog2 = 53,
                RegisterIncrement = 54,
                RegisterPeriod = 55,
                RegisterAlarm1 = 39,
                RegisterAlarm2 = 40,
                RegisterAlarm3 = 41,
                RegisterOffset = 516,
                RegisterConstant = 517,
                RegisterValue = 518,
                RegisterCalibrationPeriod = 519,
                IsCalibration = false,
                IsReserved = false,
                ReservedAddress = null,
            },
            new ModbusParametrModel
            {
                Id = 9,
                ParametrName = "SO2 (0 - 1 000 ppb)",
                GroupId = 2,
                CalibrationGroupId = 7,
                DeviceAddress = 1,
                RegisterCurrentValue = 19,
                RegisterPorog1 = 76,
                RegisterPorog2 = 77,
                RegisterIncrement = 78,
                RegisterPeriod = 79,
                RegisterAlarm1 = 57,
                RegisterAlarm2 = 58,
                RegisterAlarm3 = 59,
                RegisterOffset = 524,
                RegisterConstant = 525,
                RegisterValue = 526,
                RegisterCalibrationPeriod = 527,
                IsCalibration = false,
                IsReserved = false,
                ReservedAddress = null,
            },
            new ModbusParametrModel
            {
                Id = 10,
                ParametrName = "CO2 (0 - 5 000 ppm)",
                GroupId = 2,
                CalibrationGroupId = 7,
                DeviceAddress = 1,
                RegisterCurrentValue = 11,
                RegisterPorog1 = 44,
                RegisterPorog2 = 45,
                RegisterIncrement = 46,
                RegisterPeriod = 47,
                RegisterAlarm1 = 33,
                RegisterAlarm2 = 34,
                RegisterAlarm3 = 35,
                RegisterOffset = 532,
                RegisterConstant = 533,
                RegisterValue = 534,
                RegisterCalibrationPeriod = 535,
                IsCalibration = true,
                IsReserved = false,


                ReservedAddress = null,
            },
            new ModbusParametrModel
            {
                Id = 11,
                ParametrName = "ЛОС (0 - 10 000 ppb)",
                GroupId = 2,
                CalibrationGroupId = 8,
                DeviceAddress = 1,
                RegisterCurrentValue = 8,
                RegisterPorog1 = 32,
                RegisterPorog2 = 33,
                RegisterIncrement = 34,
                RegisterPeriod = 35,
                RegisterAlarm1 = 24,
                RegisterAlarm2 = 25,
                RegisterAlarm3 = 26,
                RegisterOffset = 545,
                RegisterConstant = 546,
                RegisterValue = 547,
                RegisterCalibrationPeriod = 529,
                IsCalibration = true,
                IsReserved = false,
                ReservedAddress = null,
            },
            new ModbusParametrModel
            {
                Id = 12,
                ParametrName = "PM 1.0 (0 - 1000 мкг / м³)",
                GroupId = 3,
                CalibrationGroupId = 8,
                DeviceAddress = 2,
                RegisterCurrentValue = 16,
                RegisterPorog1 = 40,
                RegisterPorog2 = 41,
                RegisterIncrement = 42,
                RegisterPeriod = 43,
                RegisterAlarm1 = 48,
                RegisterAlarm2 = 49,
                RegisterAlarm3 = 50,
                RegisterOffset = null,
                RegisterConstant = null,
                RegisterValue = null,
                RegisterCalibrationPeriod = null,
                IsCalibration = false,
                IsReserved = false,
                ReservedAddress = null,
            },
            new ModbusParametrModel
            {
                Id = 13,
                ParametrName = "PM 2.5 (0 - 1000 мкг / м³)",
                GroupId = 3,
                CalibrationGroupId = 8,
                DeviceAddress = 2,
                RegisterCurrentValue = 17,
                RegisterPorog1 = 68,
                RegisterPorog2 = 69,
                RegisterIncrement = 70,
                RegisterPeriod = 71,
                RegisterAlarm1 = 51,
                RegisterAlarm2 = 52,
                RegisterAlarm3 = 53,
                RegisterOffset = 545,
                RegisterConstant = 546,
                RegisterValue = 547,
                RegisterCalibrationPeriod = 530,
                IsCalibration = true,
                IsReserved = false,
                ReservedAddress = null,
            },
            new ModbusParametrModel
            {
                Id = 14,
                ParametrName = "PM 10 (0 - 1000 мкг / м³)",
                GroupId = 3,
                CalibrationGroupId = 8,
                DeviceAddress = 2,
                RegisterCurrentValue = 18,
                RegisterPorog1 = 72,
                RegisterPorog2 = 73,
                RegisterIncrement = 74,
                RegisterPeriod = 75,
                RegisterAlarm1 = 54,
                RegisterAlarm2 = 55,
                RegisterAlarm3 = 56,
                RegisterOffset = 549,
                RegisterConstant = 550,
                RegisterValue = 551,
                RegisterCalibrationPeriod = 531,
                IsCalibration = true,
                IsReserved = false,
                ReservedAddress = null,
            },
            new ModbusParametrModel
            {
                Id = 15,
                ParametrName = "Микроусорение (0 - 10 м/с)",
                GroupId = 4,
                DeviceAddress = 1,
                RegisterCurrentValue = 21,
                RegisterPorog1 = 84,
                RegisterPorog2 = 85,
                RegisterIncrement = 86,
                RegisterPeriod = 87,
                RegisterAlarm1 = 63,
                RegisterAlarm2 = 64,
                RegisterAlarm3 = 65,
                RegisterOffset = null,
                RegisterConstant = null,
                RegisterValue = null,
                RegisterCalibrationPeriod = null,
                IsCalibration = false,


                IsReserved = false,
                ReservedAddress = null,
            },
            new ModbusParametrModel
            {
                Id = 16,
                ParametrName = "Наклон (0 - 45°)",
                GroupId = 4,
                DeviceAddress = 1,
                RegisterCurrentValue = 20,
                RegisterPorog1 = 80,
                RegisterPorog2 = 81,
                RegisterIncrement = 82,
                RegisterPeriod = 83,
                RegisterAlarm1 = 60,
                RegisterAlarm2 = 61,
                RegisterAlarm3 = 62,
                RegisterOffset = null,
                RegisterConstant = null,
                RegisterValue = null,
                RegisterCalibrationPeriod = null,
                IsCalibration = false,
                IsReserved = false,
                ReservedAddress = null,
            },
            new ModbusParametrModel
            {
                Id = 17,
                ParametrName = "Взлом (0 - 100 %)",
                GroupId = 4,
                DeviceAddress = 3,
                RegisterCurrentValue = 2,
                RegisterPorog1 = 8,
                RegisterPorog2 = 9,
                RegisterIncrement = 10,
                RegisterPeriod = 11,
                RegisterAlarm1 = 6,
                RegisterAlarm2 = 7,
                RegisterAlarm3 = 8,
                RegisterOffset = 532,
                RegisterConstant = 533,
                RegisterValue = 534,
                RegisterCalibrationPeriod = 535,
                IsCalibration = true,
                IsReserved = false,
                ReservedAddress = null,
            },
            new ModbusParametrModel
            {
                Id = 18,
                ParametrName = "Температура (- 45 до +45°С)",
                GroupId = 5,
                CalibrationGroupId = 9,
                DeviceAddress = 1,
                RegisterCurrentValue = 5,
                RegisterPorog1 = 20,
                RegisterPorog2 = 21,
                RegisterIncrement = 22,
                RegisterPeriod = 23,
                RegisterAlarm1 = 15,
                RegisterAlarm2 = 16,
                RegisterAlarm3 = 17,
                RegisterOffset = 258,
                RegisterConstant = 259,
                RegisterValue = 260,
                RegisterCalibrationPeriod = 261,
                IsCalibration = true,
                IsReserved = false,
                ReservedAddress = null,
            },
            new ModbusParametrModel
            {
                Id = 19,
                ParametrName = "Отн. влажность (0 - 98 %)",
                GroupId = 5,
                CalibrationGroupId = 9,
                DeviceAddress = 1,
                RegisterCurrentValue = 6,
                RegisterPorog1 = 24,
                RegisterPorog2 = 25,
                RegisterIncrement = 26,
                RegisterPeriod = 27,
                RegisterAlarm1 = 18,
                RegisterAlarm2 = 19,
                RegisterAlarm3 = 20,
                RegisterOffset = 258,
                RegisterConstant = 259,
                RegisterValue = 260,
                RegisterCalibrationPeriod = 261,
                IsCalibration = true,
                IsReserved = true,
                ReservedAddress = 3,
            },
            new ModbusParametrModel
            {
                Id = 20,
                ParametrName = "Напряжение (8 - 16 В)",
                GroupId = 5,
                DeviceAddress = 1,
                RegisterCurrentValue = 2,
                RegisterPorog1 = 8,
                RegisterPorog2 = 9,
                RegisterIncrement = 10,
                RegisterPeriod = 11,
                RegisterAlarm1 = 6,
                RegisterAlarm2 = 7,
                RegisterAlarm3 = 8,
                RegisterOffset = null,
                RegisterConstant = null,
                RegisterValue = null,
                RegisterCalibrationPeriod = null,
                IsCalibration = false,
                IsReserved = false,
                ReservedAddress = null,
            },


            new ModbusParametrModel
            {
                Id = 21,
                ParametrName = "Скор. потока (0 - 1 л/мин)",
                GroupId = 5,
                DeviceAddress = 3,
                RegisterCurrentValue = 25,
                RegisterPorog1 = 100,
                RegisterPorog2 = 101,
                RegisterIncrement = 102,
                RegisterPeriod = 103,
                RegisterAlarm1 = 75,
                RegisterAlarm2 = 76,
                RegisterAlarm3 = 77,
                RegisterOffset = 536,
                RegisterConstant = 537,
                RegisterValue = 538,
                RegisterCalibrationPeriod = 539,
                IsCalibration = true,
                IsReserved = false,
                ReservedAddress = null,
            }
        );
        }
    }
}
